- hosts: localhost
  gather_facts: false

  vars:
    git_dest: /etc/lab
    git_src: git@github.com:pewo/lab.git

  tasks:

  #
  # Get some facts
  #
  - setup:
      gather_subset:
        - min

  - set_fact:
     #ip: "{{ (lookup('file', {{ git_dest }}/{{ ansible_facts.fqdn }}/config) | from_json).get('network') }}"
     ip: "{{ (lookup('file', '{{ git_dest }}/{{ ansible_facts.fqdn }}/config') | from_json).get('network') }}"

  - debug: var=ip
  - meta: end_play
  #
  # Update git repo
  #
  - name: get config from git
    git:
      repo: "{{ git_src }}"
      dest: "{{ git_dest }}"
    register: repo

  #
  # End playbook if repo is unchanged
  #
  - block:
    - debug:
        msg: "Repo is unchanged, exiting playbook"

    #- meta: end_play

    when: repo.changed is defined and repo.changed == false
    


    #ansible_facts.fqdn
#  - debug: var=ansible_facts.fqdn

  - name: Optionally, at the same time specify IPv6 addresses for the device
    community.general.nmcli:
      conn_name: ens19
      ifname: ens19
      type: ethernet
      ip4: 10.0.0.128/24
      #gw4: 192.0.2.1
      state: present
    register: net


  - block:

    - debug: var=net

    when: net.changed is defined and net.changed == true
