- hosts: localhost
  gather_facts: false

  vars:
    git_dest: /etc/lab
    git_src: git@github.com:pewo/lab.git

  tasks:

  #
  # Get some facts
  #
  - setup:
      gather_subset:
        - network

  - set_fact:
      config: "{{ git_dest }}/{{ ansible_facts.fqdn }}/config"
      #config: "/tmp/csv"

  - name: "Check config file {{ config }}"
    stat:
      path: "{{ config }}"
    register: st

  - debug: var=st

  - fail:
     msg: "Something wrong or missing configuration file {{ config }}"
    when: st.stat.exists is defined and ( st.stat.exists == false or st.stat.isreg == false )

  - set_fact:
      network: "{{ lookup('csvfile','network file={{ config }} delimiter=: col=1') | trim }}"
      interface: "{{ lookup('csvfile','interface file={{ config }} delimiter=: col=1') | trim }}"
      routing: "{{ lookup('csvfile','routing file={{ config }} delimiter=: col=1') | trim }}"

  - assert:
      that:
        - network | length > 0
        - interface | length > 0
      quiet: true


  - fail:
     msg: "Not allowed to change primary interface {{ ansible_facts.default_ipv4.interface }}"
    when: ansible_facts.default_ipv4.interface == interface


  - meta: end_play

  #
  # Update git repo
  #
  - name: get config from git
    git:
      repo: "{{ git_src }}"
      dest: "{{ git_dest }}"
    register: repo

  - set_fact:
     #ip: "{{ (lookup('file', '{{ git_dest }}/{{ ansible_facts.fqdn }}/ip')) }}"
     ip: "{{ (lookup('file', '/tmp/ipx')) }}"

  - debug: var=ip

  - fail: 
      msg: "The ip address {{ ip  }} is not valid"
    when: not ( ip | regex_search('^[0-9]+.[0-9]+.[0-9]+.[0-9]+\\/[0-9]+$') )


  - meta: end_play

  #
  # End playbook if repo is unchanged
  #
  - block:
    - debug:
        msg: "Repo is unchanged, exiting playbook"

    #- meta: end_play

    when: repo.changed is defined and repo.changed == false
    


    #ansible_facts.fqdn
#  - debug: var=ansible_facts.fqdn

  - name: Optionally, at the same time specify IPv6 addresses for the device
    community.general.nmcli:
      conn_name: ens19
      ifname: ens19
      type: ethernet
      ip4: 10.0.0.128/24
      #gw4: 192.0.2.1
      state: present
    register: net


  - block:

    - debug: var=net

    when: net.changed is defined and net.changed == true
