---
- hosts: lab01.wirdemo.com
  gather_facts: true
  roles:
  - role: versionlock
    tags: versionlock
    vars:
      versionlocks:
        - regex: crun-0
          package: 'crun-0:1.4.*'
        - regex: podman-1
          package: 'podman-1:3.4.*'
        - regex: podman-catatonit-1
          package: 'podman-catatonit-1:3.4.*'

       
